# Generated by Django 4.2.14 on 2024-07-29 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='address of home')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_houses', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='houses.house')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_number', models.PositiveIntegerField()),
                ('num_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarded_entrances', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='houses.house')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_number', models.PositiveIntegerField()),
                ('floor_number', models.PositiveIntegerField(blank=True, null=True)),
                ('num_of_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='houses.entrance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='entrance',
            constraint=models.UniqueConstraint(fields=('house', 'entrance_number'), name='unique_entrance_per_house'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('entrance', 'apartment_number'), name='unique_apartment'),
        ),
    ]
