# Generated by Django 4.2.14 on 2024-07-29 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0002_alter_entrance_guard_alter_house_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='resident',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Resident'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to=settings.AUTH_USER_MODEL),
        ),
    ]
